image: alpine/latest
packages:
  - emacs-nox
  - make
tasks:
  - check: |
      cd zoxide.el
      export CI_PROJECT_DIR=$(pwd)
      make check
  - build: |
      cd zoxide.el
      export CI_PROJECT_DIR=$(pwd)
      make
