#+title: Zoxide.el
#+author: Vonfry

Find file and open directory in special directory with zoxide.

* Functions
  - ~zoxide-find-file~ :: find file under a path saved in zoxide. The path is
    set to default-directory for callback.
  - ~zoxide-find-file-with-query~ :: find file under a path matching query
  - ~zoxide-travel~ :: travel to a path saved in zoxide. The path is the first
    argument passing to callback.
  - ~zoxide-travel-with-query~ :: travel to a path matching query
  - ~zoxide-cd~ :: change working directory to a path
  - ~zoxide-cd-with-query~ :: change working directory to a path matching query
  - ~zoxide-open-with~ :: a help function to query and open dir
  - ~zoxide-add~ :: add path into database
  - ~zoxide-remove~ :: remove path from database
  - ~zoxide-query~ :: list paths matching query
  - ~zoxide-query-all~ :: list all paths

* Usage
  Just call functions.
** Hooks
   You can add ~zoxide-add~ into serval hooks to add paths automatically, such
   as ~find-file-hook~, ~projectile-after-switch-project-hook~, etc.
* Customize
** ~zoxide-find-file-function~
   This can change the default callback function for ~zoxide-find-file~.
** ~zoxide-get-path-function~
   This can change the default action to get path for ~zoxide-remove~ and
   ~zoxide-add~ when ~path~ is nil.
** Evil
   You can bind ~zoxide-find-file~ to ~gz~ or ~gZ~ for quick jump.
** Dired/Dirvish/Ranger/...
   You can use ~zoxide-open-with~ with ~find-file~ directly or something like
   that:
   #+begin_src emacs-lisp :tangle yes
     (defun dired-jump-with-zoxide (&optional other-window)
        (interactive "P")
        (zoxide-open-with nil (lambda (file) (dired-jump other-window file)) t))
   #+end_src

