#+title: Zoxide.el
#+author: Vonfry

Find file and open directory in special directory with zoxide.
* Descriptions
  The project is public at [[https://sr.ht/~vonfry/zoxide.el/][sourcehut]], and source can be get from [[https://git.sr.ht/~vonfry/zoxide.el][here]]. Issues,
  patches and anything else can be discussed by
  [[mailto:~vonfry/zoxide.el@lists.sr.ht][mailto:~vonfry/zoxide.el@lists.sr.ht]] which lists on [[https://todo.sr.ht/~vonfry/zoxide.el][tickets]] or archived [[https://lists.sr.ht/~vonfry/zoxide.el][here]].

* Functions
  - ~zoxide-find-file~ :: find file under a path saved in zoxide. The path is
    set to ~default-directory~ and then the callback is run.
  - ~zoxide-find-file-with-query~ :: find file under a path matching query
  - ~zoxide-travel~ :: travel to a path saved in zoxide. The path is the first
    argument passing to callback.
  - ~zoxide-travel-with-query~ :: travel to a path matching query
  - ~zoxide-cd~ :: change working directory to a path
  - ~zoxide-cd-with-query~ :: change working directory to a path matching query
  - ~zoxide-add~ :: add path into database
  - ~zoxide-remove~ :: remove path from database
  - ~zoxide-query~ :: list all paths. This is equal to ~(zoxide-query-with
    "-l")~.
  - ~zoxide-query-with~ :: list paths matching query. If you call it
    interactively, a buffer will be prompted. Otherwise, it returns a list of
    paths.
  - ~zoxide-open-with~ :: a help function to query and open dir. It does an
    action after zoxide-query by selecting with ~completing-read-function~.

* Usage
  Just call functions.
** Hooks
   You can add ~zoxide-add~ into serval hooks to add paths automatically, such
   as ~find-file-hook~, ~projectile-after-switch-project-hook~, etc.
* Customize
** ~zoxide-find-file-function~
   This can change the default callback function for ~zoxide-find-file~.
** ~zoxide-get-path-function~
   This can change the default action to get path for ~zoxide-remove~ and
   ~zoxide-add~ when ~path~ is nil.
** Evil
   You can bind ~zoxide-find-file~ to ~gz~ or ~gZ~ for quick jump.
** Dired/Dirvish/Ranger/...
   You can use ~zoxide-open-with~ with ~find-file~ directly or something like
   that:
   #+begin_src emacs-lisp :tangle yes
     (defun dired-jump-with-zoxide (&optional other-window)
        (interactive "P")
        (zoxide-open-with nil (lambda (file) (dired-jump other-window file)) t))
   #+end_src

